{
 "title": "kafka",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(kafka_server_replicamanager_leadercount,env)"
   },
   {
    "name": "broker_id",
    "label": "Broker",
    "query": "label_values(kafka_server_kafkaserver_brokerstate, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_log_log_size,topic)"
   },
   {
    "name": "groupId",
    "label": "消费组",
    "query": "label_values(consumer_lag, groupId)"
   },
   {
    "name": "lagGroupId",
    "label": "消费组积压明细",
    "query": "label_values(consumer_lag, groupId)"
   }
  ]
 },
 "panels": [
  { "title": "集群健康检查", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "激活状态控制器数量",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "在线broker数量",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader选举比率",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "未平衡到首选副本的数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_preferredreplicaimbalancecount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "Broker网络吞吐量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic!=\"\"}[5m]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic!=\"\"}[5m]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "在线分区数",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "离线分区数量",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "没有保持同步的分区数",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "isr小于最少同步副本的分区数",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})"
    }
   ]
  },
  { "title": "系统状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM 内存使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最近1分钟YGC次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\", gc=~'.*Young.*'} - jvm_gc_collection_seconds_count{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\", gc=~'.*Young.*'} offset 1m",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最近1分钟FGC次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\", gc=~'.*Old.*'} - jvm_gc_collection_seconds_count{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\", gc=~'.*Old.*'} offset 1m",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "消息的吞吐量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "每个Broker的消息速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个Broker每秒入站字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个Broker上每秒出站字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个topic消息速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个topic入站流量速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个topic的出站流量速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个消费组平均消费速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum((consumer_offset{job=\"kafka-exporter\",env=\"$env\", groupId=~\"$groupId\", topic=~\"$topic\"}- consumer_offset{job=\"kafka-exporter\",env=\"$env\", groupId=~\"$groupId\", topic=~\"$topic\"} offset 30s)/30) by (groupId, topic)",
     "legendFormat": "{{groupId}}(topic:{{topic}})"
    }
   ]
  },
  { "title": "消息积压", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "消息积压",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(consumer_lag{job=\"kafka-exporter\",env=\"$env\", groupId=~\"$groupId\", topic=~\"$topic\"}) by (groupId, topic)",
     "legendFormat": "{{groupId}}(topic: {{topic}})"
    }
   ]
  },
  {
   "title": "$lagGroupId 积压明细",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "consumer_lag{job=\"kafka-exporter\",env=\"$env\", groupId=\"$lagGroupId\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  { "title": "请求速率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "请求速率",
   "type": "stat",
   "description": "Total request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[5m]))"
    }
   ]
  },
  {
   "title": "生产请求速率",
   "type": "stat",
   "description": "Produce request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",request=\"Produce\"}[5m]))"
    }
   ]
  },
  {
   "title": "消费请求速率",
   "type": "stat",
   "description": "Fetch request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",request=\"FetchConsumer\"}[5m]))"
    }
   ]
  },
  {
   "title": "偏移提交请求速率",
   "type": "stat",
   "description": "Offset Commit request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",request=\"OffsetCommit\"}[5m]))"
    }
   ]
  },
  {
   "title": "元信息请求速率",
   "type": "stat",
   "description": "Metadata request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",request=\"Metadata\"}[5m]))"
    }
   ]
  },
  {
   "title": "每个topic的生产请求速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个topic的消费请求速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "线程利用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "网络线程池平均空闲比例",
   "type": "graph",
   "description": "Average fraction of time the network processor threads are idle. Values are between 0 (all resources are used) and 100 (all resources are available)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "I/0线程池平均空闲比例",
   "type": "graph",
   "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 100 (all resources are available).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_total{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "请求队列大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "响应队列大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_responsequeuesize{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\",processor=\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "ISR伸缩频次", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "ISR收缩频次",
   "type": "graph",
   "description": ": The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leaders offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrshrinkspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR扩容频次",
   "type": "graph",
   "description": ": The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leaders offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrexpandspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "日志大小", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "每个topic日志大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个broker日志大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 124 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\",topic=~\"$topic\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "消费组Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "每个协调者上的消费组数量",
   "type": "bargauge",
   "description": "Number of consumer groups per group coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_coordinator_group_groupmetadatamanager_numgroups{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "不同状态的消费组数量",
   "type": "graph",
   "description": "Number of consumer group per state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsstable{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"})",
     "legendFormat": "stable"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupspreparingrebalance{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"})",
     "legendFormat": "preparing-rebalance"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsdead{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"})",
     "legendFormat": "dead"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"})",
     "legendFormat": "completing-rebalance"
    },
    {
     "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsempty{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"})",
     "legendFormat": "empty"
    }
   ]
  },
  { "title": "连接信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "活跃连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_count{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"}) by (instance, listener)",
     "legendFormat": "{{instance}}({{listener}})"
    }
   ]
  },
  {
   "title": "不同客户端版本的连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connections{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"}) by (client_software_name, client_software_version)",
     "legendFormat": "{{client_software_name}} {{client_software_version}}"
    }
   ]
  },
  {
   "title": "每个broker的连接创建速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个broker的连接关闭速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{job=\"kafka\", env=\"$env\", instance=~\"$broker_id\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "消息转换", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "生产的消息转换速率",
   "type": "graph",
   "description": "The number of messages produced converted to match the log.message.format.version.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_producemessageconversionspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[5m]))",
     "legendFormat": "速率"
    }
   ]
  },
  {
   "title": "消费的消息转换速率",
   "type": "graph",
   "description": "The number of messages consumed converted at consumer to match the log.message.format.version.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_fetchmessageconversionspersec{job=\"kafka\",env=\"$env\",instance=~\"$broker_id\"}[5m]))",
     "legendFormat": "速率"
    }
   ]
  }
 ]
}